apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform93.fullname" . }}-config
  labels:
    {{- include "platform93.labels" . | nindent 4 }}
data:
  PLATFORM93_PUBLIC_URL: {{ .Values.publicUrl | quote }}
  PLATFORM93_LISTEN_ADDRESS: ":8093"
  PLATFORM93_MASTER_KEY_FILE: /run/platform93/master-key
  PLATFORM93_METRICS_LISTEN_ADDRESS: ":9090"
  {{- if .Values.telemetry.otlpEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.telemetry.otlpEndpoint | quote }}
  OTEL_SERVICE_NAME: platform93
  {{- end }}
