apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platform93.fullname" . }}-migrate-{{ .Release.Revision }}
  labels: {{- include "platform93.labels" . | nindent 4 }}
  annotations: { "helm.sh/hook": pre-install,pre-upgrade, "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded }
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        {{- include "platform93.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
      containers:
        - name: migrate
          image: {{ include "platform93.image" . }}
          args: ["migrate"]
          env:
            - name: PLATFORM93_DATABASE_URL
              valueFrom: { secretKeyRef: { name: {{ .Values.database.existingSecret }}, key: {{ .Values.database.urlKey }} } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: ["ALL"] } }
