apiVersion: v1
kind: Service
metadata:
  name: platform93
  labels:
    {{- include "platform93.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/name: platform93, app.kubernetes.io/component: api }
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform93
  labels:
    {{- include "platform93.labels" . | nindent 4 }}
