apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform93.fullname" . }}
  labels:
    {{- include "platform93.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "platform93.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform93.fullname" . }}
  labels:
    {{- include "platform93.labels" . | nindent 4 }}
